linuxusers:
      # This is how add users to servers
      - name: "Spyder"
        username: "spyder"
        keys:
          active:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAikwbtMgAD7S20CQveTZLBiWI21topB9N1zwG27Y1FJyI8TPg29EQwVvg83f3VyF5zmIui5ZKgs0LqOy7btemS1mav45iQJeV9MuISMAe/UV4t8xwyKJuzhQNFEWqxnXLAbLs/tLwVGr5Xac4a/jBSRlQkqeUFJZ4FlFJYik7RMLQZFMpEfx21eeXycqSeEWY51+07JeOZZ2f1+MaMG6RC0J6HFKZZGQTBvlP+yhf6BuvMz3AMtCSS1dl1PKKY6VnlwWrg4+f41lZCJllcX+hIosEj0hiB7CzbDmHJJJwq+guNBC4TxziMZ10mb8ceTGnC6gqutWFrjyge7zOHpU3ow== rsa-key-20180130"
          disabled:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsPoDM21LjBodcS3Kiq7ZDyNjFY4L03Yx2nSoSzdV7TKj00Zk8gh1hSSgI/xSDXiK+QEbfPuh/7+G3sfeDDNavjWUA1kdLve4D6MTI302C3HilK6wOZV67ezyAgdgf/VCHfx+no+bocw/05r1VamLrnFjDasWAQFFeFLaOnfQTArHQRl2Z8+4ZtZ1YQPhnleFQfEz546D3oWE1DS3vuXL1Qodz3gijtHhGnc3jaQM+7m/gg2vrcL6bc/vCtdunpA1fSQrBSx0kK4qdTWwc2LZDwKIT3YP5GthvgkFHsbCo2mNdBwWZfOBTYr5LBpz9YBcO7oVBWVEI00BdEPRFOYJL onnimonni@Onni-MacBook-Air.local"
        shell: "/bin/bash"
        state: present
      - name: "Samuel Isola"
        username: "sisola"
        keys:
          active:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAxFaKE/+qFo4/d+NV/S49Cc56r3B+eeDqlQfAuxs/q0x+TzJm65D678IEP7lfgWkubhiz9OTpzNzpss4BzoqHr2oMnf4/zMjW6GgveCKvxSIcwbfjhH3bJc6LRsqlURWPvnO+SRgQKcgo5103J1CX+4eSfJj8T8WY2Zx7mWefDlWkhFEgFCRRWw7bF8pepfNBP7Pral4n9oma5+YPOeZpIcKwqM9uSqRnkJ7UFR5nOyGaqay6RMXXBe2V/9mA15z96WsCJ4snteLqlye/6kzVUN29csvW8v61goJncO64G3bKy3URCL7rk5E4nYZg0SOgh7CoSFgqze62Z+au8o8TwQ== rsa-key-20171221"
        shell: "/bin/bash"
        state: present
      - name: "David John"
        username: "djohn"
        keys:
          active:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEArsNa+e7097OlqYU8RWlTyjsgbl10ciS4068Cmr8UvoQSxEACrQGdQf/+lgN/+whbTKeiD485X2FS3wlOjfDNtkj7LdfiZ+ByveE1/ncjEhSfD5Q3hGArbQL8amgXv6He06iocdxT1UCNqtmUTLI0KP0EKeirNfENc1mihE73afBOlUCNI5cHzLsWnOiryZ+hXxL/D/1T7bjMUyMh6dSThylA7tRfobS0K0d3fSGiy9da2LrW5pkGy7lekOM7nof6gtptCIqkJmZXcloIATnfMT0aCWZeC9Bt3zMyFimT3AC9JFS871OT5IOOy7hP+AInp67r89V7/Fu+OYxKhnfBDw== rsa-key-20171227"
        shell: "/bin/bash"
        state: present
