$ANSIBLE_VAULT;1.1;AES256
62353731633363663162336461303730303135643831616138653833653863623761363636393563
3963646538353534306136303537653361396437613661380a626134343631643761643061623261
33333662666463373862646635373661653636303833373134656437636135323531366336633662
3662633063313065650a336439346463663862336663653736386462656230656466383261666365
61326430393962623962346333643138363066636339373036383037343634623032303937353930
66363333333037663763373361633939343562316662343331656634663262373935316133666532
65393766366634306663373361306636343638616436616265333738386466303036633739336637
63316661636636643961366434663066663065633634613235383135646339306134366334393030
62636565643330373438313232373432633662363632613336343032386337626563633363356338
30376239623162333933643765656565616237643430303864313935393430613537363963626435
38666430333135633363653930323666393436643431313731373434616566346163383463643939
37666662643966313838386436376537373939616131656234633534643265363932613931613931
3236
