$ANSIBLE_VAULT;1.1;AES256
36613930396337613362393161393633623763643130363934336438373736323732623631323536
6638396336623532303139653462363638303633353363360a363835656239643930323536343464
65646330663330646539616434333138666337363161373032633932633361393066653935383065
6466373265336164310a623463323962323966336234653365666664643039666532323231663533
30663939393064323433356530643161373434393633333739646263623033373131643061383030
30643134613135613639663034633865323535393266366561363161386333316132303537653063
63353530356230363230386162376361373665386639343937383961386438343835303332653936
32373462353333393132646365383331313239333832313130306237353136653436633937393866
34626338663662323861303637636663633936393738623737316334636566353464633964373466
62316233326161653030356335353261336135326630396339643138396237336361626638623932
65333435333062656461343636386165376238663666626233356338326234306639343966396538
30653730383238383637396566366562616263303364376538663864613439363666353162303563
63303037653436613633396533393839363935363532383331646562323665633337393661666166
37303133333561633438306437353032336235346665383161323964623735336230326136636164
38626231336131383531663436663130613262656164653661333137343766613063333130313839
38366430366235323864393131653336643835366231633661643534363962653862646661666431
34353464313030343065373835363538623466653262383462393835393032386462
