$ANSIBLE_VAULT;1.1;AES256
36623332376434643864323063623336353131626661666230656237643264326634646639333534
6535306165336436613934643766383333626236623966640a383635313935396431646263623362
30383463383330373530626535643138373732326437636637316132316162323136303363333038
6561386165656234630a613531623034316534346233383435626436663864623935313864333364
64373362623431633761313637356233646137663234623139656633303562336138636361313335
31323732373130363461666462626231363436663437646431336130396563306232316236643836
30303630343130336665333366633762336133353464376366333638616532383836366332383238
36353637653663386162383766633961353662383663323034323639313838323664663434656238
33326334306132346231353761636133313636363238326164653262356537316332393238653630
33356633653239363466393564623163303935333230653931383739636663636463653233663833
35373234393564626136666234666164393334303839646139356239353363336635636264356430
36356332303730323030366532393661643534633735383836326639353361333230383464333237
32353961363465353763353834613234376164313037393230356234376131323139
